baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-IE
name: 'Surgenor Music'
primary: true
siteGroup: 59bfcfec-3d66-4fc8-8d15-2fcb55cd17a9 # surgenormusic
sortOrder: 1
