dateModified: 1736592111
email:
  fromEmail: surgenormusic@gmail.com
  fromName: surgenormusic
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    59bfcfec-3d66-4fc8-8d15-2fcb55cd17a9: surgenormusic # surgenormusic
    a2f4260f-06c5-4050-bd84-86e3ec829e37: surgenormusic # surgenormusic
system:
  edition: solo
  live: true
  name: surgenormusic
  schemaVersion: 5.5.0.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
